### ISSUE TITLE
Test - GoMock Deprecated https://github.com/golang/mock

### ISSUE THREAD

**Issue by ahkui** [gohiei/go-ddd-demo#26]
Update, June 2023: This repo and tool are no longer maintained. Please see [go.uber.org/mock](https://github.com/uber/mock) for a maintained fork instead.

**Comment by ahkui** [comment]
Migrate to https://github.com/vektra/mockery ?

**Comment by gohiei** [comment]
No `golang/mock` has been imported in the repository.

**Comment by gohiei** [comment]
See [Ref](https://github.com/gohiei/go-ddd-demo/tree/main/docs#test)

**Comment by ahkui** [comment]
https://github.com/gohiei/go-ddd-demo/blob/main/go.sum#L114C1-L120C85

go.sum is include golang/mock data
