### ISSUE TITLE
DI package -> uber-go/fx

### ISSUE THREAD

**Issue by ahkui** [gohiei/go-ddd-demo#3]

**Comment by gohiei** [comment]
1. 目前暫時不會考慮
2. 如果要使用，應該會採用 google/wire (https://github.com/google/wire) (官方有推薦 [ref](https://go.dev/blog/wire))

 google/wire 比較偏向程式碼產生的工具，負責產生相依性的部分。
因此，暫時不考慮的地方，就是在於已經有類似的作法([ref](https://github.com/gohiei/go-ddd-demo/blob/main/internal/user/adapter/restful/factory.go))。
後續真的有必要的話，會再考慮進去。
