### ISSUE TITLE
Logger -> uber-go/zap ?

### ISSUE THREAD

**Issue by ahkui** [gohiei/go-ddd-demo#8]

**Comment by gohiei** [comment]
[uber-go/zap](https://github.com/uber-go/zap) 只是一種 logger 的實作, 與 mysql 角色相同.
因此, 我故意選擇 [zerolog](https://github.com/rs/zerolog).
若真的要選擇 uber-go/zap (想必你也作過功課), 也可以嘗試自行實作.
